---
name: Run zenload
author: Stefan Aeschbacher
description: runs zenload for 5 seconds with a cpu test
architecture: linux
services:
  zenload-container:
    build:
      context: .
      target: final

flow:
  - name: CPU-Load
    container: zenload-container
    commands:
      - type: console
        command: zenload -v -c 5
        note: Starting zenload
